### ISSUE TITLE
SotM Asia - MNL, PHL

### ISSUE THREAD

**Issue by govvin** [OSMPH/events#1]
State of the Map Asia
2016 Sep Manila, Philippines

**Comment by jenjereren** [comment]
Count me in!

**Comment by maning** [comment]
This is a go!
September 28 - OSM workshops
September 29 - ICCM plenary
September 30 - SOTM Asia track under ICCM

closing and will be tracked in another repo.

**Comment by maning** [comment]
no not yet. looking at other options.
