### ISSUE TITLE
CordAid Workshop

### ISSUE THREAD

**Issue by govvin** [OSMPH/events#4]
**Schedule:** 3rd week, March (sometime between 13-18)
**Venue:**  Coron, Palawan

Pipeline: Guiuan, EAS

To do:
- [x] Respond to email by organizer re program proposal. Clarify program objectives
- [x] Recruit team. 1 slot left.
- [x] Customize workshop program according to requirements discussed in Cebu meeting.
- [x] Add details to to https://github.com/OSMPH/continuum/issues/5

For background information, see #10

**Comment by feyeandal** [comment]
Guiuan?

**Comment by ralleon** [comment]
What happened to Palawan?

**Comment by govvin** [comment]
Edit: Sorry, that should've been Coron. Guiuan is under discussion, but not for immediate implementation.

Workshop will be feature-specific,  focused on mapping water resources, in particular implementation of 3R in their project sites. 
For reference, see attached. 
[3R_eng_optimized.pdf](https://files.zenhub.io/56d676335f52a31016484f2d)

**Comment by govvin** [comment]
Done! :sparkles:  Many thanks to @feyeandal and @ralleon 

## Remote Mapping Exercise

![image](https://cloud.githubusercontent.com/assets/5821688/13812862/6546ccd2-ebb9-11e5-813a-9765683d3300.png)
http://tasks.teachosm.org/project/158#task/68

> Would appreciate any help with validation

## Data Collection Exercise

![image](https://cloud.githubusercontent.com/assets/5821688/13812896/85c305fc-ebb9-11e5-9921-88c98fc89f0a.png)
