### ISSUE TITLE
Trainers for Cordaid Workshop. Connect to #4

### ISSUE THREAD

**Issue by govvin** [OSMPH/events#9]
Confirmed as available between 14-18 March, for the #4 .
- @feyeandal
- @ralleon 
- @govvin

Looking for one more trainer, **must be present for all training days**. (Three, or four, days. Not yet final.)

**Comment by seav** [comment]
I would have liked to join but I prefer not taking a long-ish leave while I'm still new at my job. Si @ralleon? @schadow1? @jenjereren?

**Comment by govvin** [comment]
FYI: @jenjereren jenjerenjen already begged off.  Waiting to hear back from Jay-Ar Ragub,

**Comment by ralleon** [comment]
If Jay-Ar is not available, then I'm ok to join on said dates

**Comment by govvin** [comment]
Thanks @ralleon. If I don't hear from back from him, or receive a confirmation by Monday, you're it.

**Comment by govvin** [comment]
Thanks @ralleon. If I don't hear from back from him, or receive a confirmation by Monday, you're it.

**Comment by govvin** [comment]
@ralleon , you're it. I just got word from Jay-ar, and he's not going to be available.

Btw, see #8 . ;)
